### ISSUE TITLE
Citations in figure titles display with their id in link text

### ISSUE THREAD

**Issue by FAtherden-eLife** [stencila/encoda#735] opened 2020-10-29 11:18 UTC
[Executable](https://elifesciences.org/articles/43154/executable#fig1):
<img width="945" alt="Screenshot 2020-10-29 at 09 52 22" src="https://user-images.githubusercontent.com/43879983/97552872-aeb43300-19cc-11eb-835e-15cc8bdb03ae.png">

[Original](https://elifesciences.org/articles/43154#fig1):
<img width="601" alt="Screenshot 2020-10-29 at 09 52 51" src="https://user-images.githubusercontent.com/43879983/97552878-b07df680-19cc-11eb-85bd-0dc737abee7b.png">

I assume this is an Encoda problem, but let me know if this is mistaken and I'll raise the ticket elsewhere.

**Comment by nokome** [comment] 2020-10-29 20:20
Thanks for the bug report @FAtherden-eLife. This is a duplicate of https://github.com/stencila/encoda/issues/673 which was fixed and released in v0.100.0 (:scream:) a few hours before. However, I had not yet regenerated the snapshot for the article. That has been done now: https://elife.stencila.io/article-43154/v20/.

**Closed by nokome** 2020-10-29 20:20 UTC
